### ISSUE TITLE
Don't export in Sketch 41:  Someting went 💩

### ISSUE THREAD

**Issue by bnopacheco** [mamuso/sketch-designdoc#3] opened 2016-11-14 17:51 UTC
![captura de tela 2016-11-14 as 15 49 04](https://cloud.githubusercontent.com/assets/592040/20276138/33afe9fa-aa82-11e6-9531-e8e4301a0a43.png)

**Comment by mamuso** [comment] 2016-11-14 17:52
Hi @maisumbruno, did you install the plugin using sketch toolbox?

**Comment by bnopacheco** [comment] 2016-11-14 19:30
@mamuso yes!

**Comment by mamuso** [comment] 2016-11-14 19:37
Great! 

The issue is with the MMMarkdown framework, it doesn't seem to load when you install the plugin using Sketch Toolbox. I'm working on a fix for this issue -> https://github.com/mamuso/sketch-designdoc/issues/1

In the meantime, if you want to try it, you can use the [github version](https://github.com/mamuso/sketch-designdoc/archive/master.zip).

**Closed as completed** 2016-11-14 19:38 UTC
Labels: duplicate

**Comment by bnopacheco** [comment] 2016-11-14 21:16
@mamuso  thanks! I will try.
