### ISSUE TITLE
It doesn't work when you install it with Sketch Toolbox

### ISSUE THREAD

**Issue by pansenpeter** [mamuso/sketch-designdoc#1] opened 2016-11-10 16:19 UTC
Loaded the chicken, and "Something went (wrong)":

```
{
    column = 51;
    line = 155;
    sourceURL = "/Users/wim/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Design Doc/DesignDoc.sketchplugin/Contents/Sketch/export.cocoascript";
}
```

**Comment by mamuso** [comment] 2016-11-10 20:12
Hi @pansenpeter, I just pushed a fix, if you re-download and re-install the plugin it should work :)

**Comment by holgerhubbs** [comment] 2016-11-11 18:05
I just installed the plugin (0.0.4) via Sketch Toolbox and get this error:

https://www.evernote.com/l/AAMRdXFTFBNNErAzNst_hCjuMtCXFJzhRMY

Thank you (-;

**Comment by mamuso** [comment] 2016-11-12 02:38
Hi @holgerhubbs,

The issue is with the MMMarkdown framework, it doesn't seem to load properly when you install the plugin using Sketch Toolbox. I'll dig more into this issue and I'll try to get it fixed soon.

In the meantime, if you wan to try it, you can use the [github version](https://github.com/mamuso/sketch-designdoc/archive/master.zip).

**Comment by holgerhubbs** [comment] 2016-11-12 04:20
Thank you so much! It works (-;

**Comment by pansenpeter** [comment] 2016-11-13 22:51
Thanks. Works fine!

**Comment by MildTomato** [comment] 2016-11-17 22:12
Hey Guys!

I'm still getting 

```
{
    column = 52;
    line = 182;
    sourceURL = "/Users/Jonathan/Library/Application Support/com.bohemiancoding.sketch3/Plugins/DesignDoc.sketchplugin/Contents/Sketch/export.cocoascript";
}
```

I installed it using the `DesignDoc.sketchplugin` file from github rather than sketch toolbox. I had previously had it installed with Sketch Toolbox though.

Running Sketch Version Version 41 (35326)

**Comment by mamuso** [comment] 2016-11-22 17:15
@MildTomato I tried to reproduce your issue in several computers (installing with Sketch Toolbox first, then uninstall and install from Github).

If I restart sketch after removing/installing, then it works for me in every case. Let me know if that works for you.

**Comment by mamuso** [comment] 2016-11-25 21:16
Getting some sense of progress with this issue:
- The Sketch Toolbox issue seems to be [reported a while back](https://github.com/buzzfeed/Sketch-Toolbox/issues/61), a fix is on its way.
- I reproduced the issue that @MildTomato had, and seems to be a problem related with unsaved documents. I'm fixing that too.

**Closed as completed** 2016-11-25 21:34 UTC
